version: '3'

services:
  glance:
    container_name: glance
    image: custom-glance
    volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
    restart: unless-stopped