FROM alpine:3.21

WORKDIR /app
COPY contafrica .

HEALTHCHECK --timeout=10s --start-period=60s --interval=60s \
  CMD wget --spider -q http://localhost:8080/api/healthz

EXPOSE 8080/tcp
ENTRYPOINT ["/app/contafrica", "--config", "/app/config/config.yml"]
