# Glance Configuration File

server:
  port: 8080

branding:
  title: "Mon Dashboard Personnalisé"  # Changez ce titre selon vos préférences
  hide-footer: false  # Cacher le pied de page

# Pages incluses depuis d'autres fichiers
pages:
  !include: home.yml
  !include: mor.yml
  !include: morecontent.yml
  !include: outils.yml
