# Glance Configuration File

server:
  port: 8080

branding:
  title: "My Glance Dashboard"

pages:
  - name: Home
    columns:
      - size: full
        widgets:
          - type: clock
            
          - type: hacker-news
            limit: 15
            collapse-after: 5
