# Glance Configuration File

server:
  port: 8080

branding:
  title: "My Glance Dashboard"

# Pages incluses depuis d'autres fichiers
pages:
  !include: home.yml
  !include: mor.yml
  !include: morecontent.yml
  !include: outils.yml
