# Contenu du dashboard principal

- name: Mon Dashboard
  columns:
    - size: small
      widgets:
        - type: weather
          location: Paris, France
          units: metric
          hour-format: 24h
        
        - type: bookmarks
          groups:
            - title: Services Essentiels
              color: 200 70 60
              links:
                - title: Gmail
                  url: https://mail.google.com
                  icon: si:gmail
                - title: Drive
                  url: https://drive.google.com
                  icon: si:googledrive
                - title: Calendar
                  url: https://calendar.google.com
                  icon: si:googlecalendar
            - title: Développement
              color: 140 70 50
              links:
                - title: GitHub
                  url: https://github.com
                  icon: si:github
                - title: StackOverflow
                  url: https://stackoverflow.com
                  icon: si:stackoverflow
                - title: CodePen
                  url: https://codepen.io
                  icon: si:codepen

    - size: full
      widgets:
        - type: monitor
          title: Mes Services
          sites:
            - title: Google
              url: https://google.com
              icon: si:google
            - title: GitHub
              url: https://github.com
              icon: si:github
            - title: YouTube
              url: https://youtube.com
              icon: si:youtube
            - title: Wikipedia
              url: https://wikipedia.org
              icon: si:wikipedia
        
        - type: docker-containers
          hide-by-default: false

    - size: small
      widgets:
        - type: clock
          hour-format: 24h
          timezones:
            - timezone: America/New_York
              label: New York
            - timezone: Europe/London
              label: Londres
            - timezone: Asia/Tokyo
              label: Tokyo
        
        - type: markets
          markets:
            - symbol: CAC
              name: CAC 40
            - symbol: BTC-USD
              name: Bitcoin
            - symbol: ETH-USD
              name: Ethereum
