- name: More Content
  columns:
    - size: small
      widgets:
        - type: weather
          location: London, United Kingdom
    
    - size: full
      widgets:
        - type: monitor
          sites:
            - title: Google
              url: https://google.com
            - title: GitHub
              url: https://github.com
              icon: si:github